package com.myspace.simpleprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "First Name")
	private java.lang.String first_name;
	@org.kie.api.definition.type.Label(value = "Last Name")
	private java.lang.String last_name;
	@org.kie.api.definition.type.Label(value = "Amount")
	private double amount;
	@org.kie.api.definition.type.Label(value = "Duration")
	private int duration;

	public application() {
	}

	public java.lang.String getFirst_name() {
		return this.first_name;
	}

	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getLast_name() {
		return this.last_name;
	}

	public void setLast_name(java.lang.String last_name) {
		this.last_name = last_name;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public application(java.lang.String first_name, java.lang.String last_name,
			double amount, int duration) {
		this.first_name = first_name;
		this.last_name = last_name;
		this.amount = amount;
		this.duration = duration;
	}

}