package com.myspace.simpleprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("First Name")
	private java.lang.String first_name;
	@org.kie.api.definition.type.Label("Last Name")
	private java.lang.String last_name;
	@org.kie.api.definition.type.Label("Amount")
	private double amount;
	@org.kie.api.definition.type.Label("Duration")
	private int duration;

	@org.kie.api.definition.type.Label("Email")
	private java.lang.String email;

	@org.kie.api.definition.type.Label(value = "Priority")
	private int priority;

	public application() {
	}

	public java.lang.String getFirst_name() {
		return this.first_name;
	}

	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getLast_name() {
		return this.last_name;
	}

	public void setLast_name(java.lang.String last_name) {
		this.last_name = last_name;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	public application(java.lang.String first_name, java.lang.String last_name,
			double amount, int duration, java.lang.String email, int priority) {
		this.first_name = first_name;
		this.last_name = last_name;
		this.amount = amount;
		this.duration = duration;
		this.email = email;
		this.priority = priority;
	}

}